name: calc_meta
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - appnope=0.1.4
  - asttokens=3.0.1
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - cartopy=0.25.0
  - cbsyst=0.4.9
  - cctools_osx-arm64=1024.3
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - clang=21.1.6
  - clang-21=21.1.6
  - clang_impl_osx-arm64=21.1.6
  - clang_osx-arm64=21.1.6
  - clangxx=21.1.6
  - clangxx_impl_osx-arm64=21.1.6
  - clangxx_osx-arm64=21.1.6
  - colorama=0.4.6
  - comm=0.2.3
  - compiler-rt=21.1.6
  - compiler-rt21=21.1.6
  - compiler-rt21_osx-arm64=21.1.6
  - contourpy=1.3.3
  - cpython=3.14.0
  - curl=8.17.0
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - future=1.0.0
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.14.1
  - gfortran_impl_osx-arm64=14.3.0
  - gfortran_osx-arm64=14.3.0
  - giflib=5.2.2
  - gmp=6.3.0
  - googlemaps=4.10.0
  - graphite2=1.3.14
  - gsl=2.7
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isl=0.26
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - kgen=1.0.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld64=955.13
  - ld64_osx-arm64=955.13
  - lerc=4.0.0
  - libarchive=3.8.2
  - libasprintf=0.25.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.6
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libcxx-devel=21.1.6
  - libcxx-headers=21.1.6
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.12.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran-devel_osx-arm64=14.3.0
  - libgfortran5=15.2.0
  - libglib=2.86.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - libllvm21=21.1.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.51
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - llvm-tools=21.1.6
  - llvm-tools-21=21.1.6
  - lz4-c=1.10.0
  - lzo=2.10
  - make=4.4.1
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - mpc=1.3.1
  - mpfr=4.2.1
  - munkres=1.1.4
  - muparser=2.3.5
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openpyxl=3.1.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parso=0.8.5
  - pathlib=1.0.1
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - proj=9.7.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pymyami=2.1.1
  - pyogrio=0.12.0
  - pyparsing=3.2.5
  - pyproj=3.7.2
  - pyshp=3.0.2
  - pysocks=1.7.1
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.0
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - r-base=4.5.2
  - readline=8.2
  - requests=2.32.5
  - rpy2=3.6.4
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - shapely=2.1.2
  - sigtool=0.1.3
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tapi=1300.6.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - uncertainties=3.2.3
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - widgetsnbextension=4.0.15
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
