# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
_python_abi3_support=1.0=hd8ed1ab_2
_r-mutex=1.0.1=anacondar_1
appnope=0.1.4=pyhd8ed1ab_1
asttokens=3.0.0=pyhd8ed1ab_1
blosc=1.21.6=h7dd00d9_1
branca=0.8.2=pyhd8ed1ab_0
brotli=1.1.0=h6caf38d_4
brotli-bin=1.1.0=h6caf38d_4
brotli-python=1.1.0=py314he8615de_4
bwidget=1.10.1=hce30654_1
bzip2=1.0.8=hd037594_8
c-ares=1.34.5=h5505292_0
ca-certificates=2025.11.12=hbd8a1cb_0
cairo=1.18.4=h6a3b0d2_0
calcification-meta-analysis=0.0.1=pypi_0
cartopy=0.25.0=py314ha3d490a_1
cbsyst=0.4.9=pyhd8ed1ab_1
cctools_osx-arm64=1024.3=llvm21_1_haddd2d4_5
certifi=2025.11.12=pyhd8ed1ab_0
cffi=2.0.0=py314hb14574c_0
charset-normalizer=3.4.4=pyhd8ed1ab_0
clang=21.1.3=default_hf9bcbb7_0
clang-21=21.1.3=default_h489deba_0
clang_impl_osx-arm64=21.1.3=h3492924_25
clang_osx-arm64=21.1.3=h07b0088_25
clangxx=21.1.3=default_h36137df_0
clangxx_impl_osx-arm64=21.1.3=h03b555f_25
clangxx_osx-arm64=21.1.3=h07b0088_25
colorama=0.4.6=pyhd8ed1ab_1
comm=0.2.3=pyhe01879c_0
compiler-rt=21.1.3=hce30654_0
compiler-rt21=21.1.3=h855ad52_0
compiler-rt21_osx-arm64=21.1.3=h2514db7_0
contourpy=1.3.3=py314h6b18a25_2
cpython=3.14.0=py314hd8ed1ab_102
curl=8.16.0=hdece5d2_0
cycler=0.12.1=pyhd8ed1ab_1
debugpy=1.8.17=py314hac9ea21_0
decorator=5.2.1=pyhd8ed1ab_0
et_xmlfile=2.0.0=pyhd8ed1ab_1
exceptiongroup=1.3.0=pyhd8ed1ab_0
executing=2.2.1=pyhd8ed1ab_0
folium=0.20.0=pyhd8ed1ab_0
font-ttf-dejavu-sans-mono=2.37=hab24e00_0
font-ttf-inconsolata=3.000=h77eed37_0
font-ttf-source-code-pro=2.038=h77eed37_0
font-ttf-ubuntu=0.83=h77eed37_3
fontconfig=2.15.0=h1383a14_1
fonts-conda-ecosystem=1=0
fonts-conda-forge=1=0
fonttools=4.60.1=pyh7db6752_0
freetype=2.14.1=hce30654_0
freexl=2.0.0=h3ab3353_2
fribidi=1.0.16=hc919400_0
future=1.0.0=pyhd8ed1ab_2
geopandas=1.1.1=pyhd8ed1ab_1
geopandas-base=1.1.1=pyha770c72_1
geos=3.14.0=h4bcf65f_0
gfortran_impl_osx-arm64=14.3.0=h6d03799_1
gfortran_osx-arm64=14.3.0=h3c33bd0_0
giflib=5.2.2=h93a5062_0
gmp=6.3.0=h7bae524_2
googlemaps=4.10.0=pyhd8ed1ab_2
graphite2=1.3.14=hec049ff_2
gsl=2.7=h6e638da_0
h2=4.3.0=pyhcf101f3_0
harfbuzz=12.1.0=haf38c7b_0
hpack=4.1.0=pyhd8ed1ab_0
hyperframe=6.1.0=pyhd8ed1ab_0
icu=75.1=hfee45f7_0
idna=3.11=pyhd8ed1ab_0
importlib-metadata=8.7.0=pyhe01879c_1
ipykernel=7.0.1=pyh5552912_0
ipython=9.6.0=pyhfa0c392_0
ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
ipywidgets=8.1.7=pyhd8ed1ab_0
isl=0.26=imath32_h347afa1_101
jedi=0.19.2=pyhd8ed1ab_1
jinja2=3.1.6=pyhd8ed1ab_0
joblib=1.5.2=pyhd8ed1ab_0
json-c=0.18=he4178ee_0
jupyter_client=8.6.3=pyhd8ed1ab_1
jupyter_core=5.9.1=pyhc90fa1f_0
jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
kgen=1.0.1=pyhd8ed1ab_0
kiwisolver=1.4.9=py314hb140f16_1
krb5=1.21.3=h237132a_0
lcms2=2.17=h7eeda09_0
ld64=955.13=h5d6df6c_5
ld64_osx-arm64=955.13=llvm21_1_hde6573c_5
lerc=4.0.0=hd64df32_1
libarchive=3.8.2=gpl_h46575ef_100
libasprintf=0.25.1=h493aca8_0
libblas=3.9.0=37_h51639a9_openblas
libbrotlicommon=1.1.0=h6caf38d_4
libbrotlidec=1.1.0=h6caf38d_4
libbrotlienc=1.1.0=h6caf38d_4
libcblas=3.9.0=37_hb0561ab_openblas
libclang-cpp21.1=21.1.3=default_h73dfc95_0
libcurl=8.16.0=hdece5d2_0
libcxx=21.1.4=hf598326_0
libcxx-devel=21.1.4=h6dc3340_0
libdeflate=1.24=h5773f1b_0
libedit=3.1.20250104=pl5321hafb1f1b_0
libev=4.33=h93a5062_2
libexpat=2.7.1=hec049ff_0
libffi=3.4.6=h1da3d7d_1
libfreetype=2.14.1=hce30654_0
libfreetype6=2.14.1=h6da58f4_0
libgdal-core=3.11.4=h339de7d_5
libgettextpo=0.25.1=h493aca8_0
libgfortran=15.2.0=hfcf01ff_1
libgfortran-devel_osx-arm64=14.3.0=hc965647_1
libgfortran5=15.2.0=h742603c_1
libglib=2.86.0=h1bb475b_0
libhwy=1.3.0=h48b13b8_1
libiconv=1.18=h23cfdf5_2
libintl=0.25.1=h493aca8_0
libjpeg-turbo=3.1.0=h5505292_0
libjxl=0.11.1=h7274d02_4
libkml=1.3.0=hc33e383_1022
liblapack=3.9.0=37_hd9741b5_openblas
libllvm21=21.1.3=h8e0c9ce_0
liblzma=5.8.1=h39f12f2_2
libmpdec=4.0.0=h5505292_0
libnghttp2=1.67.0=hc438710_0
libopenblas=0.3.30=openmp_ha158390_2
libpng=1.6.50=h280e0eb_1
librttopo=1.1.0=hf7cb3ef_19
libsodium=1.0.20=h99b78c6_0
libspatialite=5.1.0=gpl_he9e465b_118
libsqlite=3.50.4=h4237e3c_0
libssh2=1.11.1=h1590b86_0
libtiff=4.7.1=h7dc4979_0
libwebp-base=1.6.0=h07db88b_0
libxcb=1.17.0=hdb1d25a_0
libxml2=2.15.1=h9329255_0
libxml2-16=2.15.1=h0ff4647_0
libxml2-devel=2.15.1=h9329255_0
libzlib=1.3.1=h8359307_2
llvm-openmp=21.1.4=h4a912ad_0
llvm-tools=21.1.3=h855ad52_0
llvm-tools-21=21.1.3=h91fd4e7_0
lz4-c=1.10.0=h286801f_1
lzo=2.10=h925e9cb_1002
make=4.4.1=hc9fafa5_2
mapclassify=2.10.0=pyhd8ed1ab_1
markupsafe=3.0.3=pyh7db6752_0
matplotlib=3.10.7=py314he55896b_0
matplotlib-base=3.10.7=py314hd63e3f0_0
matplotlib-inline=0.1.7=pyhd8ed1ab_1
minizip=4.0.10=hff1a8ea_0
mpc=1.3.1=h8f1351a_1
mpfr=4.2.1=hb693164_3
munkres=1.1.4=pyhd8ed1ab_1
muparser=2.3.5=h11e0b38_0
ncurses=6.5=h5e97a16_3
nest-asyncio=1.6.0=pyhd8ed1ab_1
networkx=3.5=pyhe01879c_0
numpy=2.3.4=py314h5b5928d_0
openjpeg=2.5.3=h889cd5d_1
openpyxl=3.1.5=py314h6dd25ec_2
openssl=3.6.0=h5503f6c_0
packaging=25.0=pyh29332c3_1
pandas=2.3.3=py314ha3d490a_1
pango=1.56.4=h875632e_0
parso=0.8.5=pyhcf101f3_0
pathlib=1.0.1=py_1
patsy=1.0.2=pyhcf101f3_0
pcre2=10.46=h7125dd6_0
pexpect=4.9.0=pyhd8ed1ab_1
pickleshare=0.7.5=pyhd8ed1ab_1004
pillow=11.3.0=py314haf93fec_3
pip=25.2=pyh145f28c_0
pixman=0.46.4=h81086ad_1
platformdirs=4.5.0=pyhcf101f3_0
proj=9.7.0=hf83150c_0
prompt-toolkit=3.0.52=pyha770c72_0
psutil=7.1.1=py314h0612a62_0
pthread-stubs=0.4=hd74edd7_1002
ptyprocess=0.7.0=pyhd8ed1ab_1
pure_eval=0.2.3=pyhd8ed1ab_1
pycparser=2.22=pyh29332c3_1
pygments=2.19.2=pyhd8ed1ab_0
pymyami=2.1.1=pyhd8ed1ab_0
pyogrio=0.11.1=py314h7a22fc4_1
pyparsing=3.2.5=pyhcf101f3_0
pyproj=3.7.2=py314h87291f3_2
pyshp=3.0.2=pyhd8ed1ab_0
pysocks=1.7.1=pyha55dd90_7
python=3.14.0=h8929636_101_cp314
python-dateutil=2.9.0.post0=pyhe01879c_2
python-gil=3.14.0=h4df99d1_102
python-tzdata=2025.2=pyhd8ed1ab_0
python_abi=3.14=8_cp314
pytz=2025.2=pyhd8ed1ab_0
pyyaml=6.0.3=pyh7db6752_0
pyzmq=27.1.0=py312hd65ceae_0
qhull=2020.2=h420ef59_5
r-base=4.4.3=hb7b3c91_4
readline=8.2=h1d1bf99_2
requests=2.32.5=pyhd8ed1ab_0
rpy2=3.6.4=py314r44h77b1809_1
rpy2-rinterface=3.6.3=pypi_0
rpy2-robjects=3.6.3=pypi_0
scikit-learn=1.7.2=py314hcc665ce_0
scipy=1.16.2=py314h624bdf2_0
seaborn=0.13.2=hd8ed1ab_3
seaborn-base=0.13.2=pyhd8ed1ab_3
setuptools=80.9.0=pyhff2d567_0
shapely=2.1.2=py314hea0bf76_0
sigtool=0.1.3=h44b9a77_0
six=1.17.0=pyhe01879c_1
snappy=1.2.2=hd121638_0
sqlite=3.50.4=hb5dd463_0
stack_data=0.6.3=pyhd8ed1ab_1
statsmodels=0.14.5=py314hdcf55e8_1
tapi=1300.6.5=h03f4b80_0
threadpoolctl=3.6.0=pyhecae5ae_0
tk=8.6.13=h892fb3f_2
tktable=2.10=h3c7de25_7
tornado=6.5.2=py314hb84d1df_1
tqdm=4.67.1=pyhd8ed1ab_1
traitlets=5.14.3=pyhd8ed1ab_1
typing_extensions=4.15.0=pyhcf101f3_0
tzdata=2025b=h78e105d_0
tzlocal=5.3.1=pyh8f84b5b_0
uncertainties=3.2.3=pyhd8ed1ab_0
unicodedata2=16.0.0=py314hb84d1df_1
uriparser=0.9.8=h00cdb27_0
urllib3=2.5.0=pyhd8ed1ab_0
wcwidth=0.2.14=pyhd8ed1ab_0
widgetsnbextension=4.0.14=pyhd8ed1ab_0
xerces-c=3.2.5=h92fc2f4_2
xorg-libxau=1.0.12=h5505292_0
xorg-libxdmcp=1.1.5=hd74edd7_0
xyzservices=2025.4.0=pyhd8ed1ab_0
yaml=0.2.5=h925e9cb_3
zeromq=4.3.5=h888dc83_9
zipp=3.23.0=pyhd8ed1ab_0
zlib=1.3.1=h8359307_2
zstandard=0.25.0=py314h163e31d_0
zstd=1.5.7=h6491c7d_2
